// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models;

public partial class BloodComponent
{
    public Guid ComponentId { get; set; }

    public string ComponentName { get; set; }

    public string CompatibilityRules { get; set; }

    public string StorageRequirements { get; set; }

    public virtual ICollection<BloodUnit> BloodUnits { get; set; } = new List<BloodUnit>();
}