// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models;

public partial class Donor
{
    public Guid DonorId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? BloodTypeId { get; set; }

    public double? Weight { get; set; }

    public double? Height { get; set; }

    public string MedicalHistory { get; set; }

    public bool? IsAvailable { get; set; }

    public DateOnly? LastDonationDate { get; set; }

    public DateOnly? NextEligibleDate { get; set; }

    public Guid? LocationId { get; set; }

    public Guid? ClosestFacilityId { get; set; }

    public virtual ICollection<BloodDonation> BloodDonations { get; set; } = new List<BloodDonation>();

    public virtual BloodType BloodType { get; set; }

    public virtual MedicalFacility ClosestFacility { get; set; }

    public virtual ICollection<DonationHistory> DonationHistories { get; set; } = new List<DonationHistory>();

    public virtual Location Location { get; set; }

    public virtual ICollection<MedicalFacility> MedicalFacilities { get; set; } = new List<MedicalFacility>();

    public virtual User User { get; set; }
}